#!/bin/bash
function net()
{
INTERFACE="wlan0 wlan1 eth0 "
for i in $INTERFACE ;do 
if /sbin/ifconfig "$i" | grep -Fw UP >/dev/null
then
  export 	$i="down_$i:sudo ifdown $i"
else
  export  $i="up_$i:sudo ifup $i"
fi
done 
}
net
9menu -warp -popup -geometry -0+20 -fg green -bg gray20 "$wlan0"  "$wlan1"  "$eth0"  "wifi:sudo wpa_gui"  "poweroff:sudo poweroff"  "reboot:sudo reboot"  
