#!/bin/sh

status=`amixer sget Master |grep 'Mono: Playback'|sed -e 's/[\[,%]/ /g'|awk '{print $4}'`
case $1 in
 +)
    killall -9 osd_cat 
    amixer -c 0 set Master 2dB+
    osd_cat -b percentage -p middle -P $status  -d 1 -c green
  ;;
 -)
    killall -9 osd_cat 
    amixer -c 0 set Master 2dB-
    osd_cat -b percentage -p middle -P $status -d 1 -c red 

;;
 *)
  echo "usage: $0 (-|+)"
  exit 1
esac
